Document: nfhook
Title: Debian nfhook Manual
Author: <insert document author here>
Abstract: This manual describes what nfhook is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/nfhook/nfhook.sgml.gz

Format: postscript
Files: /usr/share/doc/nfhook/nfhook.ps.gz

Format: text
Files: /usr/share/doc/nfhook/nfhook.text.gz

Format: HTML
Index: /usr/share/doc/nfhook/html/index.html
Files: /usr/share/doc/nfhook/html/*.html

  
